version: "3"

services:
  apisix:
    image: apache/apisix:3.4.1-debian
    restart: always
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9180:9180/tcp"
    networks:
      - apisix
    depends_on:
      - etcd
  etcd:
    image: rancher/coreos-etcd:v3.4.15-arm64
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd-data
    environment:
      ETCD_UNSUPPORTED_ARCH: "arm64"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_DATA_DIR: "/etcd-data"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix
  redis:
    image: redis:7.0
    command: /bin/sh -c "redis-server --requirepass password"
    ports:
      - "6379:6379"
    networks:
      - apisix
  upstream:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - apisix
networks:
  apisix:
    driver: bridge
